services:
  - type: web
    name: anus-ai
    env: python
    buildCommand: ./build.sh
    startCommand: streamlit run anus/frontend.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000 