services:
  - type: web
    name: anus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python minimal_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
    healthCheckPath: /health 