services:
  - type: web
    name: anus-ai
    env: python
    buildCommand: pip install --upgrade pip && ./build.sh
    startCommand: python -m anus.server
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckTimeout: 100
    buildFilter:
      paths:
        - "anus/**"
        - "requirements.txt"
        - "build.sh"
        - "render.yaml"
        - "pyproject.toml" 