services:
  - type: web
    name: anus-ai
    env: python
    buildCommand: ./build.sh
    startCommand: streamlit run anus/frontend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000 