services:
  - type: web
    name: anus-ai
    env: python
    buildCommand: ./build.sh
    startCommand: python -m anus.server
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000 